# install list

winget install Microsoft.PowerToys
winget install Git.Git
winget install Kitware.CMake
winget install vim.vim
winget install GNU.Emacs
winget install marha.VcXsrv
winget install Graphviz.Graphviz
winget install Python.Python
winget install StrawberryPerl.StrawberryPerl
winget install RubyInstallerTeam.Ruby
winget install OpenJS.NodeJS
winget install Google.Chrome
winget install Mozilla.Firefox
winget install Microsoft.Edge
winget install VideoLAN.VLC
winget install WiresharkFoundation.Wireshark
winget install Microsoft.VisualStudioCode-User-x64
winget install Microsoft.VisualStudio.Community
winget install CPUID.GPU-Z
winget install TechPowerUpCPU-Z
